mlmprovisions/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mlmtools/', include('mlmtools.urls'))
]

mlmtools/urls.py
from django.conf.urls import url, include
from mlmtools.views import list_codes, code_detail, node_detail

urlpatterns = [
    url("^list_codes/", list_codes, name="list_codes"),
    url("^code_detail/(?P<code>[A-Za-z0-9]{4,15})/", code_detail, name="code_detail"),
    url("^node_detail/(?P<pk>[0-9]+)/", node_detail, name="node_detail"),
]

mlmtools/models.py
import decimal

from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import ugettext as _
from treenode.models import TreeNodeModel
from django.utils.timezone import now


class TrackCode(models.Model):
    node = models.ForeignKey('MarketerNode', null=True, blank=True, on_delete=models.CASCADE)
    code = models.CharField(max_length=64, db_index=True, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    valid_from = models.DateField(null=True, blank=True)
    valid_until = models.DateField(null=True, blank=True)
    USAGE_CHOICES = ( ("always", _("always",)),
                      ("useronce", _("Nx / user")),
                      ("once", _("Nx / global")))
    usage = models.CharField(max_length=8, choices=USAGE_CHOICES, default="useronce")
    max_n = models.PositiveIntegerField(default=1, help_text=_("The maximum number of codes applied to usage choices"))
    discount = models.DecimalField(default=10, decimal_places=2, max_digits=5)
    DISCOUNT_TYPE_CHOICES = ( ("perc", "%"),
                              ("CZK", "CZK"))
    discount_type = models.CharField(max_length=4, choices=DISCOUNT_TYPE_CHOICES, default="perc", verbose_name="dt")

    def __str__(self):
        return self.code

    @property
    def num_used(self):
        return self.codeuse_set.count()


class MarketerNode(TreeNodeModel):
    treenode_display_field = 'name'
    name              = models.CharField(max_length=256)
    owner             = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    SPLIT_TYPE_CHOICES = ( ( "fixed", _("fixed"),),
                           ( "treesplit", _("tree split")) )
    split_type        = models.CharField(max_length=16, choices=SPLIT_TYPE_CHOICES, default="fixed", help_text=_("How to split, fixed amount (1 level), or tree split (recursively sent up the tree)"))
    split_cut         = models.DecimalField(default=100.0, decimal_places=2, max_digits=5, help_text=_("% of split between THIS one and other"))
    can_have_children = models.BooleanField(default=True)

    @property
    def node_cut(self):
        return self.split_cut

    @property
    def sub_cut(self):
        return 100-self.split_cut

    def max_available(self, value=1.0):
        value = decimal.Decimal(value)
        for n in self.ancestors:
            if n.split_type == "fixed":
                value*= n.sub_cut/100
        return value

    @property
    def max_discount(self):
        return self.max_available(100)

    def my_cut(self, value=1.0):
        if self.parent == None:
            return value * self.split_cut/100
        value = self.max_available(value)
        if self.split_type == "treesplit" and self.parent and self.parent.split_type== "treesplit":
            return value * self.sub_cut/100
        return value

    def provision_min(self, value=1.0):
        if self.split_type == "treesplit":
            mc = self.max_available(value)
            for i in range(0,self.depth):
                mc-= mc*self.sub_cut/100
            if self.parent and self.parent.split_type!= "treesplit":
                return mc
            else:
                return mc*self.sub_cut/100
        else:
            value = decimal.Decimal(value)
            for n in self.ancestors:
                value*=n.sub_cut/100
            if self.parent:
                return value*self.node_cut/100
            else: #top level
                return value*self.sub_cut/100

    def save(self, *args, **kwargs):
        if self.parent and self.parent.split_type == "treesplit":
            self.split_type = self.parent.split_type
            self.split_cut = self.parent.split_cut
        for n in self.children:
            n.split_type = self.split_type
            n.split_cut = self.split_cut
            n.save()
        return super(MarketerNode, self).save(*args, **kwargs)


    def get_tree_split_ancestors(self):
        ancs = []
        if self.split_type == "treesplit":
            # yield self
            for anc in self.ancestors[::-1]:
                if anc.split_type != "treesplit":
                    break
                ancs.append(anc)
        return ancs


    def subpath(self, subnode):
        if subnode == self:
            return []
        ret = [subnode]
        for x in subnode.ancestors[::-1]:
            if x==self:
                break
            ret.append(x)
        return ret[::-1]


    def split_the_spoils(self, amount, cash_node, discount=0.0):
        ''' Splits the amount based on the tree. self is cashing and casher_node is the one who made the deal'''
        amount = decimal.Decimal(amount)
        if not self.parent:
            return amount*(self.split_cut/100)
        cut_for_node = cash_node.my_cut(100) - discount
        cash_node_cut = amount*(cut_for_node/100)
        if self==cash_node:
            return cash_node_cut
        currnode = cash_node
        if self.split_type == "treesplit":
            tree_split_ancestors = cash_node.get_tree_split_ancestors()
            upcut = cash_node.max_available(100)

            for x in tree_split_ancestors:
                upcut-= upcut*self.sub_cut/100
                if x == self and self.parent.split_type == "treesplit":
                    return amount * upcut / 100 * x.sub_cut / 100
            return amount*upcut/100
        else:
            return self.provision_min(amount)


    def get_provisions_for_period(self, start, end):
        ''' Generates report of code usage in the timeframe '''
        my_provisions = []
        scope = [self] + self.descendants
        subids = [d.id for d in self.descendants]
        for cu in CodeUse.objects.filter(code__node__in=scope).filter(used_at__gt=start, used_at__lte=end):
            cash_node = cu.code.node
            for_me = self.split_the_spoils(cu.amount, cash_node, cu.code.discount)
            my_provisions.append( (cu, for_me, self.subpath(cash_node)) )
        return my_provisions

    def get_sum_provisions_for_period(self, start, end):
        ''' Gets the total provisions for this node, from this node and its subnodes'''
        total = decimal.Decimal(0.0)
        for cu, provision, subpath in self.get_provisions_for_period(start, end):
            total+= provision
        return total

    def get_provisions_tree_for_period(self, start, end):
        ''' return list of (node, depth, individual provision, individual inherited provision, node's inherited provision)'''
        scope = [self] + self.descendants
        accumulator = {}
        for node in scope:
            if node not in accumulator:
                accumulator[node] = decimal.Decimal(0.0)
        for cu, provision, subpath in self.get_provisions_for_period(start, end):
            accumulator[cu.code.node]+= provision
        ret = [ ( self, 0, accumulator[self] ) ]
        for x in self.descendants:
            ret.append( (x, x.level-self.level, accumulator[x]) )
        return ret

class CodeUse(models.Model):
    code = models.ForeignKey(TrackCode, on_delete=models.DO_NOTHING)
    content_type = models.ForeignKey(ContentType, on_delete=models.DO_NOTHING, null=True)
    object_id = models.PositiveIntegerField(null=True)
    content_object = GenericForeignKey('content_type', 'object_id')
    user = models.ForeignKey(User, null=True, on_delete=models.DO_NOTHING)
    used_at = models.DateTimeField(auto_now=True, db_index=True)
    amount = models.DecimalField(default=10, decimal_places=2, max_digits=10)

    def can_be_used(self):
        ''' this method should be called before save '''
        if self.code.valid_from and self.code.valid_from > now().date():
            return False
        if self.code.valid_until and self.code.valid_until <= now().date():
            return False
        if self.code.usage == "once":
            if CodeUse.objects.filter(code=self.code).count() >= self.code.max_n:
                return False
        elif self.code.usage == "useronce":
            if CodeUse.objects.filter(code=self.code, user=self.user).count() >= self.code.max_n:
                return False
        #TODO can be applied to target
        return True

    @classmethod
    def test_use(cls, code_str, user, target=None, amount=0):
        ''' Test if the string code can be used for the desired user
        :param code_str - string of the discount code
        :param user - the Django user to map to
        :param target - the object this discount is referring to (usually the Order)
        :param amount - the original amount to calculate the discount '''
        try:
            code = TrackCode.objects.get(code__iexact=code_str)
        except TrackCode.DoesNotExist:
            return False, decimal.Decimal(0.0)
        cu = CodeUse(code=code, content_object=target, user=user, amount=amount)
        return cu.can_be_used(), cu.discounted_amount

    @classmethod
    def use(cls, code_str, user, target=None, amount=0):
        ''' Test if the string code can be used for the desired user
        :param code_str - string of the discount code
        :param user - the Django user to map to
        :param target - the object this discount is referring to (usually the Order)
        :param amount - the original amount to calculate the discount '''
        code = TrackCode.objects.get(code__iexact=code_str)
        cu = CodeUse(code=code, content_object=target, user=user, amount=amount)
        assert cu.can_be_used(), "This code can not be used"
        cu.save()

    def get_provision(self):
        ''' Gets the provision for this node '''
        cash_node = self.code.node
        return cash_node.split_the_spoils(self.amount, cash_node, self.code.discount) #TODO discount type

    def get_ancestor_provisions(self):
        cash_node = self.code.node
        discount = self.code.discount

mlmtools/forms.py
# -*- coding: utf-8 -*-
import floppyforms
from django import forms
from treenode.utils import split_pks
from .models import MarketerNode




class MarketerNodeForm(forms.ModelForm):
    split_cut = forms.DecimalField(min_value=0, max_value=100)
    class Meta:
        model = MarketerNode
        exclude = []

        # def __init__(self, *args, **kwargs):
        #     super(MarketerNodeForm, self).__init__(*args, **kwargs)
        # if 'tn_parent' not in self.fields:
        #     return
        # exclude_pks = []
        # obj = self.instance
        # if obj.pk:
        #     exclude_pks += [obj.pk]
        #     exclude_pks += split_pks(obj.tn_descendants_pks)
        # manager = obj.__class__.objects
        # self.fields['tn_parent'].queryset = manager.exclude(pk__in=exclude_pks)

mlmtools/views.py
from datetime import timedelta
from django.contrib.admin.views.decorators import staff_member_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import render
from datetime import datetime
from django.views import View
from mlmtools.models import TrackCode, MarketerNode

def get_granted_node_ids(request):
    ''' Returns list of ids the current user is allowed to see '''
    if request.user.is_superuser:
        return [ x["pk"] for x in MarketerNode.objects.all().values('pk') ]
    node_ids = []
    for node in MarketerNode.objects.filter(owner=request.user):
        node_ids += [node.pk] + [nn.pk for nn in node.descendants]
    return node_ids

@staff_member_required
def list_codes(request):
    node_ids = get_granted_node_ids(request)
    c = {"code_list" : TrackCode.objects.filter(node_id__in=node_ids),
         "granted_node_ids" : node_ids}
    return render(request, "mlmtools/list_codes.html", c)

@staff_member_required
def code_detail(request, code):
    c = { "code" : TrackCode.objects.get(code=code)}
    c["granted_node_ids"] = get_granted_node_ids(request)
    if c["code"].node.pk not in c["granted_node_ids"]:
        raise PermissionDenied("not allowed to view this node")
    if request.GET.get("since"):
        request.session["since"] = request.GET.get("since")
    if request.GET.get("until"):
        request.session["until"] = request.GET.get("until")
    c["since"] = request.session.get("since", (datetime.now().date() - timedelta(days=30)).isoformat())
    c["until"] = request.session.get("until", (datetime.now().date() + timedelta(days=3)).isoformat())
    c["usages"] = c["code"].codeuse_set.filter(used_at__gte=c["since"], used_at__lt=c["until"]).order_by("-used_at")
    return render(request, "mlmtools/code_detail.html", c)

@staff_member_required
def node_detail(request, pk):
    c = {"node" : MarketerNode.objects.get(id=pk)}
    c["granted_node_ids"] = get_granted_node_ids(request)
    if c["node"].pk not in c["granted_node_ids"]:
        raise PermissionDenied("not allowed to view this node")
    if request.GET.get("since"):
        request.session["since"] = request.GET.get("since")
    if request.GET.get("until"):
        request.session["until"] = request.GET.get("until")
    c["since"] = request.session.get("since", (datetime.now().date() - timedelta(days=30)).isoformat())
    c["until"] = request.session.get("until", (datetime.now().date() + timedelta(days=3)).isoformat())
    c["provisions"] = c["node"].get_provisions_for_period(c["since"], c["until"])
    c["provisions_tree"] = c["node"].get_provisions_tree_for_period(c["since"], c["until"])
    c["total_provisions"] = c["node"].get_sum_provisions_for_period(c["since"], c["until"])
    return render(request, "mlmtools/node_detail.html", c)

mlmtools/templates/mlmtools/code_detail.html
{% extends "base.html" %}
{% block extrahead %}{{ block.super }}
<style>
tbody.odd {
    background-color: rgba(0,0,0,.05);
}
.subtable {background-color: rgba(255,255,255,1);}
</style>
{% endblock %}
{% block content %}
<h2>{{ code }}</h2>
    <table class="table table-striped">
    <tr>
        <td colspan="2" class="text-right">
            <div class="form-inline float-right">
            <form action="." method="get">
                <input type="date" class="form-control" name="since" value="{{ since }}"/> -
                <input type="date" class="form-control" name="until" value="{{ until }}"/>
                <input type="submit" class="form-control" name="go" value="go">
            </form>
            </div>
        </td>
    </tr>
    <tr>
        <td>node</td>
        <td>{{ code.node.name }}</td>
    </tr>
    <tr>
        <td>ancestors</td>
        <td><small class="text-muted">({% for a in code.node.ancestors %}{% if a.pk in granted_node_ids %}<a href="{% url "node_detail" a.pk %}">{{ a.name }}</a>{% else %}{{ a.name }}{% endif %}{% if not forloop.last %} / {% endif %}{% endfor %})</small></td>
    </tr>
    <tr>
        <td>validity</td>
        <td>{{ code.valid_from|default_if_none:"" }} - {{ code.valid_until|default_if_none:"" }}</td>
    </tr>
    <tr>
        <td>usage count</td>
        <td>{{ code.num_used }}</td>
    </tr>
    <tr>
        <td>usage</td>
        <td>{{ code.get_usage_display }}</td>
    </tr>
    <tr>
        <td>discount</td>
        <td>{{ code.discount }}&nbsp;{{ code.get_discount_type_display }}</td>
    </tr>
    </table>


    <h3>Usages</h3>
<table class="table ">
<thead>
  <tr>
      <th>used at</th>
      <th>used for</th>
      <th>original amount</th>
      <th>client</th>
      <th>cut</th>
  </tr>
</thead>
{% for u in usages %}
    <tbody class="{% cycle "odd" "even" %}">
    <tr>
        <td>{{ u.used_at }}</td>
        <td>{{ u.content_object }}</td>
        <td>{{ u.amount }}</td>
        <td>{{ u.user }}</td>
        <td>{{ u.get_provision|floatformat:2 }}</td>
    </tr>
    <tr>
        <td></td>
        <td colspan="4"><table class="subtable table-sm table-bordered">
        {% for ancestor, provision in u.get_ancestor_provisions %}
            <tr>
                <td>{% for x in ""|ljust:forloop.counter %}&nbsp;&nbsp;{% endfor %}{% if ancestor.id in granted_node_ids %}<a href="{% url "node_detail" ancestor.pk %}">{{ ancestor.name }}</a>{% else %}<i>-hidden-</i>{% endif %}</td>
                <td>{% if ancestor.id in granted_node_ids %}{{ provision|floatformat:2 }}{% else %}-{% endif %}</td>
            </tr>
        {% endfor %}
        <tr>
            <td><i>discount</i></td>
            <td>{{ u.discounted_amount|floatformat:2 }}</td>
        </tr>
        <tr>
            <td>TOTAL</td>
            <td>{{ u.control_sum|floatformat:2 }}</td>
        </tr>
        </table></td>
    </tr>
    </tbody>
{% endfor %}
</table>
{% endblock %}

mlmtools/templates/mlmtools/list_codes.html
{% extends "base.html" %}
{% block content %}
<table class="table table-striped">
  <thead>
    <tr>
        <th>code</th>
        <th>node</th>
        <th>valid_from</th>
        <th>valid_until</th>
        <th>num_used</th>
    </tr>
  </thead>
    {%  for code in code_list %}
      <tr>
          <td style="font-family: monospace"><a href="{% url "code_detail" code.code  %}">{{ code.code }}</a></td>
          <td>{% if code.node_id %}
              <a href="{% url "node_detail" code.node.pk %}">{{ code.node.name }}</a><br>
              <small class="text-muted">({% for a in code.node.ancestors %}{% if a.pk in granted_node_ids %}<a href="{% url "node_detail" a.pk %}">{{ a.name }}</a>{% else %}{{ a.name }}{% endif %}{% if not forloop.last %} / {% endif %}{% endfor %})</small>
              {% endif %}
          </td>
          <td>{{ code.valid_from|default_if_none:"" }}</td>
          <td>{{ code.valid_until|default_if_none:"" }}</td>
          <td>{{ code.num_used }}</td>
      </tr>
    {% endfor %}
</table>

{% endblock %}

mlmtools/templates/mlmtools/node_detail.html
{% extends "base.html" %}
{% load static %}
{% block extrahead %}{{ block.super }}
<style>
tbody.odd {
    background-color: rgba(0,0,0,.05);
}
.subtable {background-color: rgba(255,255,255,1);}
</style>
    <link href="{% static "/treenode/css/treenode.css" %}" type="text/css" media="all" rel="stylesheet">
    <script src="{% static "/treenode/js/treenode.js" %}"></script>
{% endblock %}
{% block content %}
<h2>{{ node.name }}</h2>
    <table class="table table-striped">
    <tr>
        <td colspan="2" class="text-right">
            <div class="form-inline float-right">
            <form action="." method="get">
                <input type="date" class="form-control" name="since" value="{{ since }}"/> -
                <input type="date" class="form-control" name="until" value="{{ until }}"/>
                <input type="submit" class="form-control" name="go" value="go">
            </form>
            </div>
        </td>
    </tr>
    <tr>
        <td>name</td>
        <td>{{ node.name }}</td>
    </tr>
    <tr>
        <td>ancestors</td>
        <td><small class="text-muted">({% for a in node.ancestors %}{% if a.pk in granted_node_ids %}<a href="{% url "node_detail" a.pk %}">{{ a.name }}</a>{% else %}{{ a.name }}{% endif %}{% if not forloop.last %} / {% endif %}{% endfor %})</small></td>
    </tr>
    <tr>
        <td>split</td>
        <td>{{ node.node_cut|floatformat:2 }} / {{ node.sub_cut|floatformat:2 }}</td>
    </tr>
    <tr>
        <td>total provisions</td>
        <td>{{ total_provisions|floatformat:2 }}</td>
    </tr>
    </table>

    <h3>Node provision totals</h3>
<table class="table table-striped">
{% for node, depth, sum in provisions_tree %}
    <tr>
        <td>{% for x in ""|ljust:depth %}&nbsp;&nbsp;{% endfor %}<a href="{% url "node_detail" node.id %}">{{ node.name }}</a></td>
        <td>{{ sum|floatformat:2 }}</td>
    </tr>
{% endfor %}
</table>


    <h3>Provisions</h3>
<table class="table table-sm">
<thead>
  <tr>
      <th>code</th>
      <th>used at</th>
      <th>used for</th>
      <th>amount</th>
      <th>cut</th>
      <th>source</th>
  </tr>
</thead>
{% for u, provision, source in provisions %}
    <tbody class="{% cycle "odd" "even" %}">
    <tr>
        <td><a href="{% url "code_detail" u.code.code %}">{{ u.code.code }}</a></td>
        <td>{{ u.used_at }}</td>
        <td>{{ u.content_object }}</td>
        <td>{{ u.amount }}</td>
        <td>{{ provision|floatformat:2 }}</td>
        <td>({% for a in source %}<a href="{% url "node_detail" a.pk %}">{{ a.name }}</a>{% if not forloop.last %} / {% endif %}{% endfor %})</td>
    </tr>
    </tbody>
{% endfor %}
</table>
{% endblock %}

mlmtools/templates/mlmtools/tester.html
{% extends base.html %}